name: "Push containers to Docker Hub on release"

on:
  push:
    tags:
      - '*'

env:
  # 设置 docker 镜像名
  IMAGE_NAME: ghcr.io/ittoyxk
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: cp .env.example .env

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push the backend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: backend
          push: true
          platforms: |
            linux/amd64
          tags: |
            $IMAGE_NAME/hoppscotch-backend:latest
            $IMAGE_NAME/hoppscotch-backend:${{ github.ref_name }}

      - name: Build and push the frontend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: app
          push: true
          platforms: |
            linux/amd64
          tags: |
            $IMAGE_NAME/hoppscotch-app:latest
            $IMAGE_NAME/hoppscotch-app:${{ github.ref_name }}

      - name: Build and push the admin dashboard container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: sh_admin
          push: true
          platforms: |
            linux/amd64
          tags: |
            $IMAGE_NAME/hoppscotch-sh-admin:latest
            $IMAGE_NAME/hoppscotch-sh-admin:${{ github.ref_name }}

      - name: Build and push the AIO container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: aio
          push: true
          platforms: |
            linux/amd64
          tags: |
            $IMAGE_NAME/hoppscotch-aio:latest
            $IMAGE_NAME/hoppscotch-aio:${{ github.ref_name }}
